CREATE DATABASE SPMedGROUP_Manha;

USE SPMedGROUP_Manha;

CREATE TABLE Clinica(
IdClinica INT PRIMARY KEY IDENTITY,
NomeClinica VARCHAR(255) NOT NULL,
CNPJ CHAR(14) NOT NULL UNIQUE,
RazaoSocial VARCHAR(200) NOT NULL,
Logradouro VARCHAR(200) NOT NULL,
Bairro VARCHAR(200) NOT NULL,
HorarioI DATETIME NOT NULL,
HorarioF DATETIME NOT NULL
);

CREATE TABLE AreaClinica(
IdAreaClinica INT PRIMARY KEY IDENTITY,
NomeAC VARCHAR(255) NOT NULL,
IdClinica INT FOREIGN KEY REFERENCES Clinica (IdClinica)
);

CREATE TABLE Cidade(
IdCidade INT PRIMARY KEY IDENTITY,
NomeC VARCHAR(255) NOT NULL,
IdEstado INT FOREIGN KEY REFERENCES Estado (IdEstado)

);

CREATE TABLE Estado(
IdEstado INT PRIMARY KEY IDENTITY,
NomeE VARCHAR(255) NOT NULL
);

CREATE TABLE Medico(
IdMedico INT PRIMARY KEY IDENTITY,
NomeM VARCHAR(255) NOT NULL,
CRM CHAR() NOT NULL,
IdUsuario INT FOREIGN KEY REFERENCES Usuario (IdUsuario),
IdAreaClinica INT FOREIGN KEY REFERENCES AreaClinica (IdAreaClinica)
);

CREATE TABLE Consulta(
IdConsulta INT PRIMARY KEY IDENTITY,
DataAgendamento DATETIME NOT NULL,
Descricao VARCHAR(255) NOT NULL,
IdProntuario INT FOREIGN KEY REFERENCES Prontuario (IdProntuario),
IdMedico INT FOREIGN KEY REFERENCES Medico (IdMedico),
IdSituacao INT FOREIGN KEY REFERENCES Situacao (IdSituacao)
);

CREATE TABLE Usuario(
IdUsuario INT PRIMARY KEY IDENTITY,
Email VARCHAR(100) NOT NULL,
Senha CHAR(10) NOT NULL
);

CREATE TABLE PerfilUsuario(
IdPerfilUsuario INT PRIMARY KEY IDENTITY,
NomePU VARCHAR(200) NOT NULL
);

CREATE TABLE Prontuario(
IdProntuario INT PRIMARY KEY IDENTITY,
NomeP VARCHAR(255) NOT NULL,
DataNascimento DATETIME NOT NULL,
Telefone CHAR(11) NOT NULL,
RG CHAR(10) NOT NULL,
CPF CHAR(11) NOT NULL,
Peso INT NOT NULL,
Altura DOUBLE(3,2) NOT NULL
);