CREATE DATABASE StoryTelling_Manha;

/*  DDL - LINGUAGEM DE DEFINIÇÃO DE DADOS */


USE StoryTelling_Manha;

CREATE TABLE T_Clinica(
	IdClinica INT PRIMARY KEY IDENTITY,
	NomeClinica VARCHAR(255) NOT NULL UNIQUE,
	Endereco VARCHAR(255) NOT NULL UNIQUE,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	Telefone CHAR(12) NOT NULL

);
GO

CREATE TABLE T_Medico(
	IdMedico INT PRIMARY KEY IDENTITY,
	NomeMedico VARCHAR(255) NOT NULL UNIQUE,
	CRM CHAR(9) NOT NULL UNIQUE,
	Genero VARCHAR(20) NOT NULL
);
GO

CREATE TABLE T_Paciente(
	IdPaciente INT PRIMARY KEY IDENTITY,
	NomePaciente VARCHAR(255) NOT NULL UNIQUE,
	Endereco VARCHAR(255) NOT NULL,
	GeneroP VARCHAR(20) NOT NULL,
	TelefoneP VARCHAR(12) NOT NULL

);
GO

CREATE TABLE T_TipoUsuario(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	TipoUsuario VARCHAR(255) NOT NULL UNIQUE
);
GO

CREATE TABLE T_Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	NomeUsuario VARCHAR(255) NOT NULL UNIQUE,
	GeneroU VARCHAR(20) NOT NULL,
	Telefone VARCHAR(12) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES T_TipoUsuario(IdTipoUsuario) NOT NULL
);
GO

CREATE TABLE T_Consulta(
	IdConsulta INT PRIMARY KEY IDENTITY,
	TipoConsulta VARCHAR(200) NOT NULL UNIQUE,
	DataConsulta DATETIME,
	IdUsuario INT FOREIGN KEY REFERENCES T_Usuario (IdUsuario) NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES T_Paciente (IdPaciente) NOT NULL
);
GO


