CREATE DATABASE StoryTelling_Manha;

/*  DDL - LINGUAGEM DE DEFINIÇÃO DE DADOS */


USE StoryTelling_Manha;

CREATE TABLE T_Clinica(
	IdClinica INT PRIMARY KEY IDENTITY,
	NomeClinica VARCHAR(255) NOT NULL UNIQUE,
	Endereco VARCHAR(255) NOT NULL UNIQUE,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	Telefone CHAR(12) NOT NULL
);
GO

CREATE TABLE T_Especialidade(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	NomeEspecialidade VARCHAR(255) NOT NULL UNIQUE,
);
GO

CREATE TABLE T_TipoUsuario(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	TipoUsuario VARCHAR(255) NOT NULL UNIQUE
);
GO

CREATE TABLE T_Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	NomeUsuario VARCHAR(255) NOT NULL UNIQUE,
	Email VARCHAR(20) NOT NULL,
	Senha VARCHAR(12) NOT NULL,
	IdTipoUsuario INT FOREIGN KEY REFERENCES T_TipoUsuario(IdTipoUsuario) NOT NULL
);
GO

CREATE TABLE T_Medico(
	IdMedico INT PRIMARY KEY IDENTITY,
	NomeMedico VARCHAR(255) NOT NULL UNIQUE,
	CRM CHAR(9) NOT NULL UNIQUE,
	Genero VARCHAR(20) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES T_Clinica(IdClinica),
	IdEspecialidade INT FOREIGN KEY REFERENCES T_Especialidade(IdEspecialidade),
	IdUsuario INT FOREIGN KEY REFERENCES T_Usuario (IdUsuario)
);
GO

CREATE TABLE T_Paciente(
	IdPaciente INT PRIMARY KEY IDENTITY,
	NomePaciente VARCHAR(255) NOT NULL UNIQUE,
	Endereco VARCHAR(255) NOT NULL,
	GeneroP VARCHAR(20) NOT NULL,
	TelefoneP VARCHAR(12) NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES T_Usuario (IdUsuario)NOT NULL
);
GO

CREATE TABLE T_Consulta(
	IdConsulta INT PRIMARY KEY IDENTITY,
	Situacao VARCHAR(255) NOT NULL UNIQUE,
	DataConsulta DATETIME,
	IdMedico INT FOREIGN KEY REFERENCES T_Medico (IdMedico) NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES T_Paciente(IdPaciente) NOT NULL
);
GO

CREATE TABLE T_ADM(
	IdADM INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES T_Usuario(IdUsuario)
);

SELECT * FROM T_Clinica;
SELECT * FROM T_Medico;
SELECT * FROM T_Especialidade;
SELECT * FROM T_Paciente;
SELECT * FROM  T_TipoUsuario;
SELECT * FROM T_Usuario;
SELECT * FROM T_Consulta;
SELECT * FROM T_ADM;

DROP TABLE T_Clinica;
DROP TABLE T_Medico;
DROP TABLE T_Especialidade;
DROP TABLE T_Paciente;
DROP TABLE T_TipoUsuario;
DROP TABLE T_Usuario;
DROP TABLE T_Consulta;
DROP TABLE T_ADM;

